### ISSUE TITLE
False positive on all websites

### ISSUE THREAD

**Issue by Neolex-Security** [ollseg/ttt-ext#1]
HI ! 
I have a false positive on every site I visit when I use your extension.

>VM16:55 Tainted postMessage call: [object Object], https://www.google.fr/?t4inT3d.param=t4inT3d.value%22%27%3ch1%3Elol#!//t4inT3d.hash%22'%3ch1%3Elol
addWarning @ VM16:55

**Comment by ollseg** [comment]
Could you try disabling all other extensions to see if that has any effect?

**Comment by Neolex-Security** [comment]
Oh yes, I just tried to remove extensions and disable one at the time and the issue comes from "Wappalyzer"
