### ISSUE TITLE
Execution fails with Request URL Too Long

### ISSUE THREAD

**Issue by rotemreiss** [ollseg/ttt-ext#3]
Hi,

First of all, I enjoyed your talk at SecuirytFest! Great talk. ❤️ 

I just tried that Chrome extension for the first time and on two different applications, I'm getting "Request URL Too Long" error from the application's web server because of one of the tests.
Is that a known issue? How can we make the tool to complete all its tests without being stopped with this error?

Thanks!

**Comment by ollseg** [comment]
I have reverted to the previous behaviour of trying to remove tainted values from the URL parameters before sending to the server. This fixes the issue at the expense of added complexity and permission requirements. Closing as fixed.

**Comment by rotemreiss** [comment]
Will update the extension on my local and test it again.
Thanks :)
